# Extract & Data Profiling

This notebook reads all raw CSV files from `data/raw`, displays the initial data contents, and creates a basic profiling summary before the transformation stage.

In [28]:
import pandas as pd
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 120)

## Path Configuration

In [29]:
PROJECT_ROOT = Path.cwd() if (Path.cwd() / 'data' / 'raw').exists() else Path.cwd().parent
RAW_DIR = PROJECT_ROOT / 'data' / 'raw'
VALIDATION_DIR = PROJECT_ROOT / 'data' / 'validation'

VALIDATION_DIR.mkdir(parents=True, exist_ok=True)

print('Raw data folder:', RAW_DIR.resolve())
print('Validation folder:', VALIDATION_DIR.resolve())

Raw data folder: C:\Codingan Kuliah\SEMESTER 6\Data Warehouse\atc-data-warehouse\data\raw
Validation folder: C:\Codingan Kuliah\SEMESTER 6\Data Warehouse\atc-data-warehouse\data\validation

## Raw CSV File Inventory

In [30]:
csv_files = sorted(RAW_DIR.glob('*.csv'))

file_inventory = pd.DataFrame({
    'file_name': [file.name for file in csv_files],
    'table_name': [file.stem for file in csv_files],
    'size_kb': [round(file.stat().st_size / 1024, 2) for file in csv_files],
})

display(file_inventory)

                        file_name                  table_name  size_kb
0       dim_channel_pembelian.csv       dim_channel_pembelian     0.17
1                  dim_lokasi.csv                  dim_lokasi     7.62
2             dim_lokasi_rows.csv             dim_lokasi_rows     7.62
3               dim_pelanggan.csv               dim_pelanggan    61.13
4                  dim_produk.csv                  dim_produk     2.61
5        dim_status_transaksi.csv        dim_status_transaksi     0.13
6                   dim_waktu.csv                   dim_waktu    40.07
7      fact_transaksi_layanan.csv      fact_transaksi_layanan  2939.76
8  fact_transaksi_layanan_fix.csv  fact_transaksi_layanan_fix  1774.02

## Extract All CSV Files

In [31]:
tables = {}

for file in csv_files:
    table_name = file.stem
    tables[table_name] = pd.read_csv(file)

print(f'Total tables loaded: {len(tables)}')
print(list(tables.keys()))

Total tables loaded: 9
['dim_channel_pembelian', 'dim_lokasi', 'dim_lokasi_rows', 'dim_pelanggan', 'dim_produk', 'dim_status_transaksi', 'dim_waktu', 'fact_transaksi_layanan', 'fact_transaksi_layanan_fix']

## CSV Content Preview

This section displays the first few rows from each CSV file.

In [32]:
for table_name, df in tables.items():
    print(f'\n=== {table_name} ===')
    print(f'Rows: {df.shape[0]:,}')
    print(f'Columns: {df.shape[1]:,}')
    display(df.head(10))

=== dim_channel_pembelian ===
Rows: 6
Columns: 3

   id_channel       nama_channel jenis_channel
0           1        MyTelkomsel       Digital
1           2            GraPARI         Fisik
2           3         Minimarket         Fisik
3           4  Website_Telkomsel       Digital
4           5       Mitra Dealer         Fisik
5           6       USSD (*888#)       Digital

=== dim_lokasi ===
Rows: 98
Columns: 7

   id_lokasi    site_id      kelurahan      kecamatan kabupaten_kota     provinsi        regional
0          1  SITE-0001        Menteng        Menteng  Jakarta Pusat  DKI Jakarta   Regional Jawa
1          2  SITE-0002         Gambir         Gambir  Jakarta Pusat  DKI Jakarta   Regional Jawa
2          3  SITE-0003    Tanah Abang    Tanah Abang  Jakarta Pusat  DKI Jakarta   Regional Jawa
3          4  SITE-0004      Kemayoran      Kemayoran  Jakarta Pusat  DKI Jakarta   Regional Jawa
4          5  SITE-0005          Senen          Senen  Jakarta Pusat  DKI Jakarta   Regional Jawa
5          6  SITE-0006           Koja           Koja  Jakarta Utara  DKI Jakarta   Regional Jawa
6          7  SITE-0007  Tanjung Priok  Tanjung Priok  Jakarta Utara  DKI Jakarta   Regional Jawa
7          8  SITE-0008    Penjaringan    Penjaringan  Jakarta Utara  DKI Jakarta   Regional Jawa
8          9  SITE-0009      Cilincing      Cilincing  Jakarta Utara  DKI Jakarta   Regional Jawa
9         10  SITE-0010     Pademangan     Pademangan  Jakarta Utara  DKI Jakarta   Regional Jawa

=== dim_lokasi_rows ===
Rows: 98
Columns: 7

   id_lokasi    site_id      kelurahan      kecamatan kabupaten_kota     provinsi        regional
0          1  SITE-0001        Menteng        Menteng  Jakarta Pusat  DKI Jakarta   Regional Jawa
1          2  SITE-0002         Gambir         Gambir  Jakarta Pusat  DKI Jakarta   Regional Jawa
2          3  SITE-0003    Tanah Abang    Tanah Abang  Jakarta Pusat  DKI Jakarta   Regional Jawa
3          4  SITE-0004      Kemayoran      Kemayoran  Jakarta Pusat  DKI Jakarta   Regional Jawa
4          5  SITE-0005          Senen          Senen  Jakarta Pusat  DKI Jakarta   Regional Jawa
5          6  SITE-0006           Koja           Koja  Jakarta Utara  DKI Jakarta   Regional Jawa
6          7  SITE-0007  Tanjung Priok  Tanjung Priok  Jakarta Utara  DKI Jakarta   Regional Jawa
7          8  SITE-0008    Penjaringan    Penjaringan  Jakarta Utara  DKI Jakarta   Regional Jawa
8          9  SITE-0009      Cilincing      Cilincing  Jakarta Utara  DKI Jakarta   Regional Jawa
9         10  SITE-0010     Pademangan     Pademangan  Jakarta Utara  DKI Jakarta   Regional Jawa

=== dim_pelanggan ===
Rows: 1,000
Columns: 7

   id_pelanggan      nomor_hp   nama_pelanggan jenis_layanan jenis_kartu tanggal_registrasi status_aktif
0             1  083126610857     Umar Maulana      Prabayar        Halo         2023-04-05            1
1             2  082290810818      Ayu Susanto    Pascabayar     simPATI         2024-05-20        FALSE
2             3  085245977945      Andi Kusuma           NaN        Halo         2023-01-19        false
3             4  082299564122     Fira Purnomo      Prabayar    Kartu As         2022-01-29        FALSE
4             5  085360122777     Wawan Rahayu           NaN        Halo         2022-02-10         true
5             6  085367899730      Luki Wijaya    Pascabayar        Loop         2024-12-17        false
6             7  082183959724    Putri Handoko    Pascabayar    Kartu As         2024-03-10        FALSE
7             8  085316743380  Dodi Firmansyah      Prabayar     simPATI         2022-02-07            1
8             9  085142891077     Putri Wijaya      Prabayar     simPATI         2022-08-16            1
9            10  085171255213   Luki Handoko!!      Prabayar        Halo         2024-06-18         true

=== dim_produk ===
Rows: 50
Columns: 6

   id_produk kode_produk     nama_produk  jenis_produk kategori_produk     harga
0          1    PRD-0001     1 GB Harian    Paket Data          Harian      2000
1          2    PRD-0002     2 GB HARIAN    Paket Data          Harian      3500
2          3    PRD-0003     5 GB Harian    Paket Data          Harian      7000
3          4    PRD-0004   1 GB Mingguan    Paket Data        Mingguan      9000
4          5    PRD-0005   3 GB Mingguan    Paket Data        Mingguan     20000
5          6    PRD-0006   5 GB Mingguan  Paket Data!!        Mingguan     30000
6          7    PRD-0007  10 GB Mingguan    Paket Data        Mingguan     50000
7          8    PRD-0008    1 GB Bulanan    Paket Data         Bulanan   2820000
8          9    PRD-0009    5 GB Bulanan    Paket Data         Bulanan     50000
9         10    PRD-0010   10 GB Bulanan    Paket Data             NaN  14450000

=== dim_status_transaksi ===
Rows: 5
Columns: 3

   id_status kode_status deskripsi_status
0          1      ST-001           Sukses
1          2      ST-002            Gagal
2          3      ST-003          Pending
3          4      ST-004           REFUND
4          5      ST-005       Dibatalkan

=== dim_waktu ===
Rows: 1,096
Columns: 6

   id_waktu tanggal_lengkap    hari    bulan kuartal   tahun
0         1      2022-01-01   Sabtu  Januari      Q1  2022.0
1         2      2022-01-02  Minggu  Januari      Q1  2022.0
2         3      2022-01-03   Senin  Januari      Q1  2022.0
3         4      2022-01-04  Selasa  Januari      Q1  2022.0
4         5      2022-01-05    Rabu  Januari      Q1  2022.0
5         6      2022-01-06   Kamis  Januari      Q1  2022.0
6         7      2022-01-07   Jumat  Januari      Q1  2022.0
7         8      2022-01-08   Sabtu  Januari      Q1  2022.0
8         9      2022-01-09  Minggu  Januari      Q1  2022.0
9        10      2022-01-10   Senin  Januari      Q1  2022.0

=== fact_transaksi_layanan ===
Rows: 50,000
Columns: 13

,id_fakta,id_waktu,id_pelanggan,id_produk,id_lokasi,id_channel,id_status,nomor_transaksi,jumlah_pembelian,total_harga,jumlah_data_mb,durasi_telpon_menit,jumlah_sms
0,1,949,214,11,4,1,1,TRX009490000001,"3,-",450000.0,36914.81,NaN,NaN
1,2,80,777,45,50,5,1,TRX000800000002,2,2000.0,54344.07,NaN,NaN
2,3,590,726,29,28,5,1,TRX005900000003,1,25000.0,NaN,NaN,624
3,4,671,243,34,14,3,1,TRX006710000004,1,200000.0,44081.52,527,223
4,5,858,793,34,68,1,1,TRX008580000005,3,600000.0,12863.57,126,372??
5,6,603,525,36,37,6,1,TRX006030000006,3,450000.0,37873.83,139,147
6,7,431,378,22,66,5,1,TRX004310000007,3,150000.0,NaN,2925,NaN
7,8,1010,279,24,74,1,1,TRX010100000008,1,70000.0,NaN,526,NaN
8,9,79,18,32,8,2,1,TRX000790000009,3,285000.0,14917.96,582,213
9,10,1001,121,10,43,3,4,TRX010010000010,1,85000.0,95281.01,NaN,NaN

=== fact_transaksi_layanan_fix ===
Rows: 25,926
Columns: 14

,Unnamed: 0,id_fakta,id_waktu,id_pelanggan,id_produk,id_lokasi,id_channel,id_status,nomor_transaksi,jumlah_pembelian,total_harga,jumlah_data_mb,durasi_telpon_menit,jumlah_sms
0,0,4,671,243,34,14,3,1,TRX006710000004,1,200000.0,44081.52,527,223
1,1,5,858,793,34,68,1,1,TRX008580000005,3,600000.0,12863.57,126,372??
2,2,6,603,525,36,37,6,1,TRX006030000006,3,450000.0,37873.83,139,147
3,3,9,79,18,32,8,2,1,TRX000790000009,3,285000.0,14917.96,582,213
4,4,15,95,798,40,88,2,1,TRX000950000015,1,10000.0,27047.78,904,259
5,5,18,1065,102,49,97,3,2,TRX010650000018,1,120000.0,45217.3,823,4
6,6,20,1062,96,44,89,5,2,TRX010620000020,1,175000.0,14330.87,318,228
7,7,22,769,275,50,76,3,1,TRX007690000022,1,200000.0,26837.35,124,275
8,8,25,762,846,30,65,3,3,TRX007620000025,1,35000.0,18382.65,752,202
9,9,29,420,191,32,86,6,1,TRX004200000029,2,190000.0,10875.43,NaN,380

## Initial Column Structure and Data Types

In [33]:
for table_name, df in tables.items():
    print(f'\n=== {table_name} ===')
    schema_df = pd.DataFrame({
        'column_name': df.columns,
        'dtype': [str(dtype) for dtype in df.dtypes],
        'non_null_count': df.notna().sum().values,
        'null_count': df.isna().sum().values,
        'null_percentage': (df.isna().mean().values * 100).round(2),
        'unique_count': df.nunique(dropna=True).values,
    })
    display(schema_df)

=== dim_channel_pembelian ===

     column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0     id_channel  int64               6           0              0.0             6
1   nama_channel    str               6           0              0.0             6
2  jenis_channel    str               6           0              0.0             2

=== dim_lokasi ===

      column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0       id_lokasi  int64              98           0             0.00            98
1         site_id    str              98           0             0.00            98
2       kelurahan    str              97           1             1.02            97
3       kecamatan    str              96           2             2.04            96
4  kabupaten_kota    str              97           1             1.02            37
5        provinsi    str              98           0             0.00            23
6        regional    str              97           1             1.02             8

=== dim_lokasi_rows ===

      column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0       id_lokasi  int64              98           0             0.00            98
1         site_id    str              98           0             0.00            98
2       kelurahan    str              97           1             1.02            97
3       kecamatan    str              96           2             2.04            96
4  kabupaten_kota    str              97           1             1.02            37
5        provinsi    str              98           0             0.00            23
6        regional    str              97           1             1.02             8

=== dim_pelanggan ===

          column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0        id_pelanggan  int64            1000           0              0.0          1000
1            nomor_hp    str             981          19              1.9           981
2      nama_pelanggan    str             988          12              1.2           597
3       jenis_layanan    str             975          25              2.5             8
4         jenis_kartu    str             977          23              2.3            16
5  tanggal_registrasi    str             988          12              1.2           687
6        status_aktif    str             976          24              2.4             6

=== dim_produk ===

       column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0        id_produk  int64              50           0              0.0            50
1      kode_produk    str              49           1              2.0            49
2      nama_produk    str              50           0              0.0            50
3     jenis_produk    str              49           1              2.0             7
4  kategori_produk    str              48           2              4.0             7
5            harga    str              50           0              0.0            34

=== dim_status_transaksi ===

        column_name  dtype  non_null_count  null_count  null_percentage  unique_count
0         id_status  int64               5           0              0.0             5
1       kode_status    str               5           0              0.0             5
2  deskripsi_status    str               5           0              0.0             5

=== dim_waktu ===

       column_name    dtype  non_null_count  null_count  null_percentage  unique_count
0         id_waktu    int64            1096           0             0.00          1096
1  tanggal_lengkap      str            1091           5             0.46          1091
2             hari      str            1096           0             0.00            22
3            bulan      str            1094           2             0.18            26
4          kuartal      str            1096           0             0.00             9
5            tahun  float64            1091           5             0.46             3

=== fact_transaksi_layanan ===

            column_name    dtype  non_null_count  null_count  null_percentage  unique_count
0              id_fakta    int64           50000           0             0.00         50000
1              id_waktu    int64           50000           0             0.00          1096
2          id_pelanggan    int64           50000           0             0.00          1000
3             id_produk    int64           50000           0             0.00            50
4             id_lokasi    int64           50000           0             0.00           100
5            id_channel    int64           50000           0             0.00             6
6             id_status    int64           50000           0             0.00             5
7       nomor_transaksi      str           50000           0             0.00         49896
8      jumlah_pembelian      str           49504         496             0.99           260
9           total_harga  float64           49492         508             1.02          1605
10       jumlah_data_mb      str           36250       13750            27.50         36173
11  durasi_telpon_menit      str           23691       26309            52.62          3320
12           jumlah_sms      str           21938       28062            56.12          1505

=== fact_transaksi_layanan_fix ===

            column_name    dtype  non_null_count  null_count  null_percentage  unique_count
0            Unnamed: 0    int64           25926           0             0.00         25926
1              id_fakta    int64           25926           0             0.00         25926
2              id_waktu    int64           25926           0             0.00          1096
3          id_pelanggan    int64           25926           0             0.00          1000
4             id_produk    int64           25926           0             0.00            50
5             id_lokasi    int64           25926           0             0.00           100
6            id_channel    int64           25926           0             0.00             6
7             id_status    int64           25926           0             0.00             5
8       nomor_transaksi      str           25926           0             0.00         25908
9      jumlah_pembelian      str           25689         237             0.91           186
10          total_harga  float64           25667         259             1.00           902
11       jumlah_data_mb      str           19679        6247            24.10         19645
12  durasi_telpon_menit      str           19445        6481            25.00          2669
13           jumlah_sms      str           19445        6481            25.00          1406

## Missing Value Check

In [34]:
for table_name, df in tables.items():
    missing_df = (
        df.isna()
        .sum()
        .reset_index()
        .rename(columns={'index': 'column_name', 0: 'missing_count'})
    )
    missing_df['missing_percentage'] = (missing_df['missing_count'] / len(df) * 100).round(2)
    missing_df = missing_df[missing_df['missing_count'] > 0]

    print(f'\n=== {table_name} ===')
    if missing_df.empty:
        print('No missing values found.')
    else:
        display(missing_df.sort_values('missing_count', ascending=False))

=== dim_channel_pembelian ===
No missing values found.

=== dim_lokasi ===

      column_name  missing_count  missing_percentage
3       kecamatan              2                2.04
2       kelurahan              1                1.02
4  kabupaten_kota              1                1.02
6        regional              1                1.02

=== dim_lokasi_rows ===

      column_name  missing_count  missing_percentage
3       kecamatan              2                2.04
2       kelurahan              1                1.02
4  kabupaten_kota              1                1.02
6        regional              1                1.02

=== dim_pelanggan ===

          column_name  missing_count  missing_percentage
3       jenis_layanan             25                 2.5
6        status_aktif             24                 2.4
4         jenis_kartu             23                 2.3
1            nomor_hp             19                 1.9
2      nama_pelanggan             12                 1.2
5  tanggal_registrasi             12                 1.2

=== dim_produk ===

       column_name  missing_count  missing_percentage
4  kategori_produk              2                 4.0
1      kode_produk              1                 2.0
3     jenis_produk              1                 2.0

=== dim_status_transaksi ===
No missing values found.

=== dim_waktu ===

       column_name  missing_count  missing_percentage
1  tanggal_lengkap              5                0.46
5            tahun              5                0.46
3            bulan              2                0.18

=== fact_transaksi_layanan ===

            column_name  missing_count  missing_percentage
12           jumlah_sms          28062               56.12
11  durasi_telpon_menit          26309               52.62
10       jumlah_data_mb          13750               27.50
9           total_harga            508                1.02
8      jumlah_pembelian            496                0.99

=== fact_transaksi_layanan_fix ===

            column_name  missing_count  missing_percentage
13           jumlah_sms           6481               25.00
12  durasi_telpon_menit           6481               25.00
11       jumlah_data_mb           6247               24.10
10          total_harga            259                1.00
9      jumlah_pembelian            237                0.91

## Duplicate Row Check

In [35]:
duplicate_summary = []

for table_name, df in tables.items():
    duplicate_rows = int(df.duplicated().sum())
    duplicate_summary.append({
        'table_name': table_name,
        'row_count': len(df),
        'duplicate_rows': duplicate_rows,
        'duplicate_percentage': round(duplicate_rows / len(df) * 100, 2) if len(df) else 0,
    })

duplicate_summary_df = pd.DataFrame(duplicate_summary)
display(duplicate_summary_df)

                   table_name  row_count  duplicate_rows  duplicate_percentage
0       dim_channel_pembelian          6               0                   0.0
1                  dim_lokasi         98               0                   0.0
2             dim_lokasi_rows         98               0                   0.0
3               dim_pelanggan       1000               0                   0.0
4                  dim_produk         50               0                   0.0
5        dim_status_transaksi          5               0                   0.0
6                   dim_waktu       1096               0                   0.0
7      fact_transaksi_layanan      50000               0                   0.0
8  fact_transaksi_layanan_fix      25926               0                   0.0

## Extract Profiling Summary

In [36]:
profile_summary = []

for table_name, df in tables.items():
    profile_summary.append({
        'table_name': table_name,
        'row_count': len(df),
        'column_count': len(df.columns),
        'total_missing_values': int(df.isna().sum().sum()),
        'duplicate_rows': int(df.duplicated().sum()),
        'columns': ', '.join(df.columns),
    })

profile_summary_df = pd.DataFrame(profile_summary)
display(profile_summary_df)

output_path = VALIDATION_DIR / 'extract_profile_summary.csv'
profile_summary_df.to_csv(output_path, index=False)

print(f'Profiling summary saved to: {output_path}')

,table_name,row_count,column_count,total_missing_values,duplicate_rows,columns
0,dim_channel_pembelian,6,3,0,0,"id_channel, nama_channel, jenis_channel"
1,dim_lokasi,98,7,5,0,"id_lokasi, site_id, kelurahan, kecamatan, kabu..."
2,dim_lokasi_rows,98,7,5,0,"id_lokasi, site_id, kelurahan, kecamatan, kabu..."
3,dim_pelanggan,1000,7,115,0,"id_pelanggan, nomor_hp, nama_pelanggan, jenis_..."
4,dim_produk,50,6,4,0,"id_produk, kode_produk, nama_produk, jenis_pro..."
5,dim_status_transaksi,5,3,0,0,"id_status, kode_status, deskripsi_status"
6,dim_waktu,1096,6,12,0,"id_waktu, tanggal_lengkap, hari, bulan, kuarta..."
7,fact_transaksi_layanan,50000,13,69125,0,"id_fakta, id_waktu, id_pelanggan, id_produk, i..."
8,fact_transaksi_layanan_fix,25926,14,19705,0,"Unnamed: 0, id_fakta, id_waktu, id_pelanggan, ..."

Profiling summary saved to: c:\Codingan Kuliah\SEMESTER 6\Data Warehouse\atc-data-warehouse\data\validation\extract_profile_summary.csv